## PART - 1 Label encoding,  One-hot encoding

In [3]:
import pandas as pd
import numpy as np

train = pd.read_csv('train.csv')

train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
train['Age'].fillna(train['Age'].mean,inplace=True)
train.drop(['Cabin'],axis=1,inplace=True)
train['Embarked'].fillna(train['Embarked'].mode()[0],inplace=True)

print(train.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    object
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     891 non-null    object
dtypes: float64(1), int64(5), object(5)
memory usage: 76.7+ KB
None

In [5]:
from sklearn.preprocessing import LabelEncoder

def func_labelencoder(list1,features):
    encode = LabelEncoder()
    features[list1] = encode.fit_transform(features[list1].astype(str))


var_le = ['Sex','Embarked']

for i in var_le:
    func_labelencoder(i,train)

In [6]:
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,22,1,0,A/5 21171,7.2500,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38,1,0,PC 17599,71.2833,0
2,3,1,3,"Heikkinen, Miss. Laina",0,26,0,0,STON/O2. 3101282,7.9250,2
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35,1,0,113803,53.1000,2
4,5,0,3,"Allen, Mr. William Henry",1,35,0,0,373450,8.0500,2

## Part - 2 One-hot Encoding

In [7]:
df = pd.read_excel('datapreprocessing.xlsx')

# Get the rows that contains NULL (NaN)
df.isnull().sum()

# Fill the NaN values for Occupation, Emplyment Status and Employement Type

col = ['Occupation','Employment Status','Employement Type']
df[col] = df[col].fillna(df.mode().iloc[0])

features = df.iloc[:,:-1].values
features1 = df.iloc[:,:-1].values

labels = df.iloc[:,-1].values
df1=pd.DataFrame(features)
df1.head()

         0   1       2         3    4          5      6
0   Poland  34    Male  Salaried  Yes  Permanent  72000
1    Spain  42  Female  Business  Yes  Temporary  48000
2  Germany  29    Male  Business   No  Temporary  54000
3    Spain  38    Male  Business   No  Permanent  61000
4  Germany  32    Male  Salaried  Yes  Permanent    NaN

In [12]:
#--------------------------- ONE HOT ENCODING --------------------------------#
from sklearn.preprocessing import OneHotEncoder

#hotencode = OneHotEncoder(categorical_features=[0])
#features = hotencode.fit_transform(features).toarray()

from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("Geography", OneHotEncoder(), [0])], remainder = 'passthrough')
features = ct.fit_transform(features)
df1=pd.DataFrame(features)
df1.head()

  0  1  2  3  4  5  6   7       8         9    10         11     12
0  1  0  0  0  0  1  0  34    Male  Salaried  Yes  Permanent  72000
1  1  0  0  0  0  0  1  42  Female  Business  Yes  Temporary  48000
2  1  0  0  1  0  0  0  29    Male  Business   No  Temporary  54000
3  1  0  0  0  0  0  1  38    Male  Business   No  Permanent  61000
4  1  0  0  1  0  0  0  32    Male  Salaried  Yes  Permanent    NaN

In [17]:
ct = ColumnTransformer([("Geography", OneHotEncoder(), [9])], remainder = 'passthrough')
features = ct.fit_transform(features)
df1=pd.DataFrame(features)
df1.head()

ValueError: Input contains NaN

In [ ]:
'''

hotencode = OneHotEncoder(categorical_features=[9])
features = hotencode.fit_transform(features).toarray()

hotencode = OneHotEncoder(categorical_features=[11])
features = hotencode.fit_transform(features).toarray()

hotencode = OneHotEncoder(categorical_features=[13])
features = hotencode.fit_transform(features).toarray()

#--

hotencode = OneHotEncoder(categorical_features=[0])
features1 = hotencode.fit_transform(features1).toarray()

hotencode = OneHotEncoder(categorical_features=[2])
features1 = hotencode.fit_transform(features1).toarray()

hotencode = OneHotEncoder(categorical_features=[3])
features1 = hotencode.fit_transform(features1).toarray()

hotencode = OneHotEncoder(categorical_features=[4])
features1 = hotencode.fit_transform(features1).toarray()

hotencode = OneHotEncoder(categorical_features=[5])
features1 = hotencode.fit_transform(features1).toarray()
'''